name: 'Run CI'

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Lint
        run: pnpm lint

  CodeQL-Analyze:
    name: CodeQL Analyze
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: github/codeql-action/init@v2
      - uses: github/codeql-action/autobuild@v2
      - uses: github/codeql-action/analyze@v2

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Type Check
        run: pnpm type-check

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Test
        run: pnpm test

  storybook-test:
    name: Storybook Test
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Build Storybook
        run: yarn build-storybook --quiet

      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:6006 && yarn test-storybook"
