name: 'Run CI'

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Cypress.io
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          build: pnpm build
          start: pnpm start
          wait-on: 'http://localhost:3000'
          spec: cypress/e2e/game.cy.ts
