name: Integration Test

on:
  pull_request:
    branches:
      - master
      - develop
      - release/**

jobs:
  integration-test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress.io
        uses: cypress-io/github-action@v2.7.0
        with:
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:3000'
          spec: cypress/integration/game.spec.ts
