name: Integration Test

on:
  pull_request:
    branches:
      - master
      - develop
      - release/**

jobs:
  integration-test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.28.0
      - name: Cypress.io
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          build: pnpm build
          start: pnpm start
          wait-on: 'http://localhost:3000'
          spec: cypress/e2e/game.cy.ts
