name: Type Check

on:
  pull_request:
    branches:
      - master
      - develop
      - release/**

jobs:
  type-check-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pnpm install
      - name: Type Check run
        run: pnpm type-check
