name: Unit Test

on:
  pull_request:
    branches:
      - master
      - develop
      - release/**

jobs:
  unit-test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.28.0
      - name: Install dependencies
        run: pnpm install
      - name: Unit test run
        run: pnpm jest
