name: Unit Test

on:
  pull_request:
    branches:
      - master
      - develop
      - release/**

jobs:
  unit-test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Unit test run
        run: yarn test
